In [1]:
import pandas as pd
import numpy as np
# plotting
import matplotlib.pyplot as plt
import seaborn as sns
# for ROC curves
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
# Evaluation
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score
# TensorFlow for deep neural neteworks
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Flatten, Conv2D, AveragePooling2D
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
import warnings

# Disable all warnings
warnings.filterwarnings("ignore")

# For Data Augmentation
from tensorflow.keras.preprocessing.image import ImageDataGenerator


In [2]:
if(tf.test.is_built_with_cuda() == True):
    print("CUDA Available.. Just wait a few moments...")
else:
    print("CUDA not Available.. May the force be with you.")

CUDA Available.. Just wait a few moments...


In [3]:
train = pd.read_csv("train.csv")
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['label'].plot(kind='hist', bins=20, title='label')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2.plot(kind='scatter', x='index', y='label', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['label']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_3.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('label')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_4.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['pixel0']
  ys = series['label']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('pixel0', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('pixel0')
_ = plt.ylabel('label')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['pixel0']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'pixel0'}, axis=1)
              .sort_values('pixel0', ascending=True))
  xs = counted['pixel0']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values('pixel0', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('pixel0')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_7['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_8['label'].plot(kind='line', figsize=(8, 4), title='label')
plt.gca().spines[['top', 'right']].set_visible(False)

In [4]:
X = train.drop(columns=['label'])
y = train['label']

In [5]:
X = X / 255.0

In [6]:
X = X.values.reshape(-1,28,28,1)

In [7]:
y = to_categorical(y, num_classes=10) #, num_classes=10

In [8]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape = (28, 28, 1))) #output (w-f+2p)/s+1  ,padding='valid'
model.add(AveragePooling2D((3,3)))

model.add(Conv2D(64, (3,3), activation='relu'))
model.add(AveragePooling2D((2,2)))
model.add(layers.Dropout(0.3))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(layers.Dropout(0.3))
model.add(Dense(10, activation="softmax"))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 26, 26, 32)          │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d (AveragePooling2D) │ (None, 8, 8, 32)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 6, 6, 64)            │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d_1                  │ (None, 3, 3, 64)            │               0 │
│ (AveragePooling2D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 3, 3, 64)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 576)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 93,962 (367.04 KB)

 Trainable params: 93,962 (367.04 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile(optimizer="SGD", loss="categorical_crossentropy", metrics=["accuracy"])  #Adam

In [21]:
early_stopping = EarlyStopping(monitor='val_loss',patience= 5 ,  restore_best_weights=True)
history = model.fit(X_train, y_train, epochs = 50, batch_size = 250, validation_data=(X_val, y_val), callbacks=[early_stopping])


Epoch 1/50
135/135 ━━━━━━━━━━━━━━━━━━━━ 7s 32ms/step - accuracy: 0.9620 - loss: 0.1206 - val_accuracy: 0.9724 - val_loss: 0.0865
Epoch 2/50
135/135 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9602 - loss: 0.1233 - val_accuracy: 0.9736 - val_loss: 0.0863
Epoch 3/50
135/135 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9603 - loss: 0.1252 - val_accuracy: 0.9732 - val_loss: 0.0860
Epoch 4/50
135/135 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9604 - loss: 0.1232 - val_accuracy: 0.9731 - val_loss: 0.0861
Epoch 5/50
135/135 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9594 - loss: 0.1270 - val_accuracy: 0.9736 - val_loss: 0.0858
Epoch 6/50
135/135 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9616 - loss: 0.1229 - val_accuracy: 0.9721 - val_loss: 0.0869
Epoch 7/50
135/135 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9632 - loss: 0.1201 - val_accuracy: 0.9733 - val_loss: 0.0853
Epoch 8/50
135/135 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9612 - loss: 0.1279 - val_accuracy: 0

In [22]:
_, acc = model.evaluate(X_val, y_val, verbose=0)
print('> %.3f' % (acc * 100.0))

> 97.595


In [25]:
test_loss, test_acc = model.evaluate(X_val, y_val, verbose=2)
print(f"Test accuracy: {test_acc*100},loos : {test_loss*100}")

263/263 - 1s - 3ms/step - accuracy: 0.9760 - loss: 0.0783
Test accuracy: 97.59523868560791,loos : 7.826255261898041


In [26]:
Y_pred = model.predict(X_val)
#print(y_val)
#accuracy = accuracy_score(y_val, y_pred)
#print(f'Accuracy: {accuracy}')
# Convert predictions classes to one hot vectors
Y_pred_classes = np.argmax(Y_pred,axis = 1)
# Convert validation observations to one hot vectors
Y_true = np.argmax(y_val,axis = 1)
# compute the confusion matrix
confusion_mtx = confusion_matrix(Y_true, Y_pred_classes)
print('confusion_mtx ',confusion_mtx)

263/263 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
confusion_mtx  [[809   0   0   1   1   1   3   0   1   0]
 [  0 902   2   0   1   0   2   1   1   0]
 [  1   3 826   5   3   0   0   2   5   1]
 [  1   1   5 904   0  11   0   5   4   6]
 [  1   0   2   0 809   0   7   2   0  18]
 [  0   0   0   7   1 689   2   0   1   2]
 [  2   1   0   0   1   0 778   0   3   0]
 [  0   1   9   0   2   0   0 869   2  10]
 [  2   3   4   5   2   3   1   3 806   6]
 [  2   3   1   8   4   3   0   8   3 806]]


In [27]:
X_test = pd.read_csv("test.csv")
X_test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [28]:
X_test = X_test/255
X_test = X_test.values.reshape(-1,28,28,1)


In [30]:

# predict results
results = model.predict(X_test)

# select the indix with the maximum probability
results = np.argmax(results,axis = 1)

results = pd.Series(results,name="Label")
print(results[0:9])

875/875 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
0    2
1    0
2    9
3    9
4    3
5    7
6    0
7    3
8    0
Name: Label, dtype: int64


In [35]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(Y_true, Y_pred_classes)
print(f'Accuracy: {accuracy}')
print(classification_report(Y_true, Y_pred_classes))

confusion_mtx = confusion_matrix(Y_true, Y_pred_classes)
print('confusion_mtx ',confusion_mtx)


Accuracy: 0.9759523809523809
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       816
           1       0.99      0.99      0.99       909
           2       0.97      0.98      0.97       846
           3       0.97      0.96      0.97       937
           4       0.98      0.96      0.97       839
           5       0.97      0.98      0.98       702
           6       0.98      0.99      0.99       785
           7       0.98      0.97      0.97       893
           8       0.98      0.97      0.97       835
           9       0.95      0.96      0.96       838

    accuracy                           0.98      8400
   macro avg       0.98      0.98      0.98      8400
weighted avg       0.98      0.98      0.98      8400

confusion_mtx  [[809   0   0   1   1   1   3   0   1   0]
 [  0 902   2   0   1   0   2   1   1   0]
 [  1   3 826   5   3   0   0   2   5   1]
 [  1   1   5 904   0  11   0   5   4   6]
 [  1   0   2   0 809   0

In [39]:
model.save('dig_model.keras')